// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjRFSPEvck2uTdVAfFl8lQ24jmfPo2Bqw',
    appId: '1:798505477777:web:3402dbafc268648c0f8130',
    messagingSenderId: '798505477777',
    projectId: 'ac-mobil-ku',
    authDomain: 'ac-mobil-ku.firebaseapp.com',
    storageBucket: 'ac-mobil-ku.firebasestorage.app',
    measurementId: 'G-7J0TC0WQ78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOalyPZ9CZ01nhO10IoldMT8J1r3yuWMg',
    appId: '1:798505477777:android:49005cddec2eb0370f8130',
    messagingSenderId: '798505477777',
    projectId: 'ac-mobil-ku',
    storageBucket: 'ac-mobil-ku.firebasestorage.app',
  );
}
